database: &DATABASE
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *DATABASE
  database: TSYC_development

test:
  <<: *DATABASE
  database: TSYC_test

staging:
  <<: *DATABASE
  database: TSYC_staging

# DATABASE_URL is added automatically
# and merged with these properties on heroku
production:
  <<: *DATABASE

